export const CONTEST_LIST_UPDATE = 'CONTEST_LIST_UPDATE';
export const GET_CONTESTS = 'GET_CONTESTS';
export const SET_SELECTED_CONTEST = 'SET_SELECTED_CONTEST';
export const GO_BACK_TO_TASKS = 'GO_BACK_TO_TASKS';
