export const MATCH_LIST_UPDATE = 'MATCH_LIST_UPDATE';
export const GET_FOOTER_MENU = 'GET_FOOTER_MENU';
export const GOTO_MENU_ITEM = 'GOTO_MENU_ITEM';
export const GOTO_TASKS = 'GOTO_TASKS';
export const GOTO_MATCHES = 'GOTO_MATCHES';

